package cn.qinguide.f5web.common.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.qinguide.f5web.common.entity.AppInfoEntity;
import cn.qinguide.f5web.common.entity.ScriptEntity;
import cn.qinguide.f5web.common.entity.XposedEntity;

import cn.qinguide.f5web.common.db.dao.AppInfoEntityDao;
import cn.qinguide.f5web.common.db.dao.ScriptEntityDao;
import cn.qinguide.f5web.common.db.dao.XposedEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig appInfoEntityDaoConfig;
    private final DaoConfig scriptEntityDaoConfig;
    private final DaoConfig xposedEntityDaoConfig;

    private final AppInfoEntityDao appInfoEntityDao;
    private final ScriptEntityDao scriptEntityDao;
    private final XposedEntityDao xposedEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        appInfoEntityDaoConfig = daoConfigMap.get(AppInfoEntityDao.class).clone();
        appInfoEntityDaoConfig.initIdentityScope(type);

        scriptEntityDaoConfig = daoConfigMap.get(ScriptEntityDao.class).clone();
        scriptEntityDaoConfig.initIdentityScope(type);

        xposedEntityDaoConfig = daoConfigMap.get(XposedEntityDao.class).clone();
        xposedEntityDaoConfig.initIdentityScope(type);

        appInfoEntityDao = new AppInfoEntityDao(appInfoEntityDaoConfig, this);
        scriptEntityDao = new ScriptEntityDao(scriptEntityDaoConfig, this);
        xposedEntityDao = new XposedEntityDao(xposedEntityDaoConfig, this);

        registerDao(AppInfoEntity.class, appInfoEntityDao);
        registerDao(ScriptEntity.class, scriptEntityDao);
        registerDao(XposedEntity.class, xposedEntityDao);
    }
    
    public void clear() {
        appInfoEntityDaoConfig.clearIdentityScope();
        scriptEntityDaoConfig.clearIdentityScope();
        xposedEntityDaoConfig.clearIdentityScope();
    }

    public AppInfoEntityDao getAppInfoEntityDao() {
        return appInfoEntityDao;
    }

    public ScriptEntityDao getScriptEntityDao() {
        return scriptEntityDao;
    }

    public XposedEntityDao getXposedEntityDao() {
        return xposedEntityDao;
    }

}
